### ISSUE TITLE
gutenbergr sometimes returns results with the wrong declared encoding

### ISSUE THREAD

**Issue by patperry** [ropensci/gutenbergr#13]
See, for example, line 15222 of Mansfield Park, which is wrongly declared to be UTF-8:

```
> library("gutenbergr")
> book <- gutenberg_download(141) # Mansfield Park
Determining mirror for Project Gutenberg from http://www.gutenberg.org/robot/harvest
Using mirror http://aleph.gutenberg.org
> line <- book$text[15222]
> line
[1] "the command of her beauty, and her \xa320,000, any one who could satisfy the"
> Encoding(line)
[1] "UTF-8"
```

Note the `\xa3`. You can fix this by either setting the correct encoding:
```
> line2 <- line
> Encoding(line2) <- "latin1"
> line2
[1] "the command of her beauty, and her £20,000, any one who could satisfy the"
```

Or, by converting from the actual encoding ("latin1") to UTF-8:
```
> iconv(line, "latin1", "UTF-8")
[1] "the command of her beauty, and her £20,000, any one who could satisfy the"
```

Alternatively, just download the UTF-8 version of the text ( http://www.gutenberg.org/files/141/141-0.txt ) instead of the version that gutenberg.org wrongly claims to be ASCII (http://www.gutenberg.org/files/141/141.txt )

More discussion at https://github.com/juliasilge/janeaustenr/issues/4

**Comment by patperry** [comment]
Here's how I went about this in another package:

1. try downloading the text with a `-0.txt` extension before `-8.txt` or `.txt`; I couldn't find documentation, but I think that `"-0"` corresponds to UTF-8 encoding

2. look for a line starting with `Character set encoding:` in the header of the file, then convert from that encoding to UTF-8 using `iconv`.

You can see all of this at https://github.com/patperry/r-corpus/blob/master/R/gutenberg.R#L51 . Feel free to take anything in that function you find useful. (I'd submit pull request, but I'm not proficient in tidyverse so you'd probably want to rewrite my code anyway.)

**Comment by jonthegeek** [comment]
It looks like this is fixed now. The character is on line 15540, but the encoding is a proper pound sign:

``` r
library(gutenbergr)
book <- gutenberg_download(141) # Mansfield Park
#> Determining mirror for Project Gutenberg from http://www.gutenberg.org/robot/harvest
#> Using mirror http://aleph.gutenberg.org
line <- book$text[15540]
line
#> [1] "heir-apparents, who were at the command of her beauty, and her £20,000,"
```

<sup>Created on 2022-11-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
