### ISSUE TITLE
Transfer to ropensci

### ISSUE THREAD

**Issue by maelle** [ropensci/gutenbergr#18]
@dgrtwo We now transfer all onboarded repos to ropensci. Would it be ok if I transferred your repo soon? Do you want me to update all links after transfer (CI links, installation instructions) or do you prefer to do it yourself?

**Comment by maelle** [comment]
:wave: @dgrtwo could I transfer the repo?

**Comment by dgrtwo** [comment]
Yes you can!

**Comment by maelle** [comment]
Thanks, done! 🎊  Please update links to this repo. 

* Reg Travis I'm still figuring out what the travis-ci.org to travis-ci.com transfer means, sorry about that, will post an update soon. 

* The new Appveyor badge is `[![Build status](https://ci.appveyor.com/api/projects/status/lqb7hngtj5epsmd1?svg=true)](https://ci.appveyor.com/project/ropensci/gutenbergr-dujv9)`
