### ISSUE TITLE
Add year field to metadata?

### ISSUE THREAD

**Issue by MichaelChirico** [ropensci/gutenbergr#24]
I'm thinking of using `gutenbergr` to create some sort of ad-hoc English word frequency table and would either filter or down-weight older usage, but there's no direct way to do so now. The `gutenberg_authors` data gives data about the authors' lifespan, which can give a crude approximation, but the year of authorship of the work itself would be more helpful.

Is this something that can be included readily?

**Comment by ZekeMarshall** [comment]
I second this request. It would be super-useful to have a metadata column containing the original publication date of each text. However, as far as I can see from the Project Gutenberg website the bibliographic record does not include this data.
