### ISSUE TITLE
What are the correct meta_fields IDs?

### ISSUE THREAD

**Issue by Marcella988** [ropensci/gutenbergr#25]
Hi! I've been trying to download certain books by ID, and I want the following meta data: title, author, author's year of birth, and author's year of death. Title and author work fine, but whenever I add birthdate and deathdate, which is what both the handbook and other websites say the IDs are for author's year of birth and death, Rstudio returns the complaint that those columns do not exist.

This is the exact code I'm trying to use:
gutenberg_download(c(56404,
                              52993,
                              44019,
                              16299
), meta_fields = c("title", "author", "birthdate", "deathdate"))

Anyone know what I'm doing wrong? Thanks!

**Comment by jmclawson** [comment]
Gutenbergr provides a few data sources; one of these has metadata about texts, and another has metadata about authors. The `gutenberg_download()` function accesses the metadata about texts, but the columns "birthdate" and "deathdate" belong to the metadata about authors.

Assuming you're using `dplyr`, the following code will allow you to combine these two data sets into the table you're looking for:

```r
gutenberg_download(c(56404, 52993, 44019, 16299), 
meta_fields = c("title", "author")) %>% 
full_join(gutenberg_authors[,c("author", "birthdate", "deathdate")], by = "author")
```
