### ISSUE TITLE
CRAN version later than dev version

### ISSUE THREAD

**Issue by Myfanwy** [ropensci/gutenbergr#29]
Hi @dgrtwo , @maelle , @noamross : I was hoping to update `gutenberg_metadata` and make a pull request, but noted that the CRAN version is later than the github, is there somewhere else the package is being developed?  

Filing this here at Noam's suggestion (he also mentioned something called 'commitment escalation', whatever that is... probably nothing ;-) )

**Comment by noamross** [comment]
Closed by 9d2453859e2b12b00a583cbcd1f410a99a627417
