### ISSUE TITLE
Removed from CRAN -  New Maintainer Needed

### ISSUE THREAD

**Issue by jonthegeek** [ropensci/gutenbergr#30]
A [book club we're about to start at R4DS](https://github.com/r4ds/bookclub-mnetanal) uses this package, which led me to find that it's archived on CRAN. Is there anything we can do to get it back up? I think this is used for examples in a lot of things, so I want to help revive it if I can!

Looking at the notes, I *think* this is one of the things that can be auto-fixed via the latest version of roxygen2.

**Comment by Myfanwy** [comment]
I am willing to be the new maintainer but should probably be the last choice if there are other options, as I have neither python nor web-scraping chops.

**Comment by jonthegeek** [comment]
@Myfanwy I can help with the refactor, but at least for now I'd rather not own it. Deal?

**Comment by Myfanwy** [comment]
@jonthegeek  deal :).

**Comment by maelle** [comment]
You should now both have access to this repository. Thank you!

**Comment by maelle** [comment]
Regarding the process, _if I am not mistaken_, once you have a release candidate (see https://github.com/ThinkR-open/prepare-for-cran + https://usethis.r-lib.org/reference/use_release_issue.html),
- the former maintainer should email CRAN with you in cc;
- you submit the package but make sure the CRAN comments explain how the new submission solves the problem from https://cran-archive.r-project.org/web/checks/2022/2022-10-03_check_results_gutenbergr.html (I found this via https://cran.r-project.org/web/packages/policies.html#Re_002dsubmission-1)

**Comment by maelle** [comment]
@jonthegeek @Myfanwy what email address should our community manager @yabellini use for inviting you to rOpenSci slack workspace?

**Comment by maelle** [comment]
Feel free to ping me with any question!

**Comment by jonthegeek** [comment]
> @jonthegeek @Myfanwy what email address should our community manager @yabellini use for inviting you to rOpenSci slack workspace?

jonthegeek@gmail.com. Thanks!

**Comment by maelle** [comment]
(note that slack invites are sent in batch ~ weekly)

**Comment by Myfanwy** [comment]
I accepted the invite, thanks @maelle!  I’m in the field through the end of the week will check back when I’m in the office

**Comment by jonthegeek** [comment]
I'm working on some cleanup right now. Nothing major functionality-wise, but I'm trying to get it to an easier-to-maintain state. Hopefully that'll make it easier for you to take over, @Myfanwy !

**Comment by JosiahParry** [comment]
Came here to report this issue! I see this is being handled! :) let me know if there is anything I can do to help get this back onto cran.

**Comment by maelle** [comment]
And please ping me if any help is needed @jonthegeek @Myfanwy :smile_cat:

**Comment by Myfanwy** [comment]
I think we're close to having a release candidate - goal is to have it submitted by next week. @maelle @dgrtwo should I email you directly when it's ready so we can do the maintainer switch?

**Comment by dgrtwo** [comment]
Sure! In my understanding all I'll have to do is respond to a single email from CRAN. Really appreciate all of your hard work taking this over.

**Comment by Myfanwy** [comment]
Complete in fce55e0d7443e2260602d8ae430db67865cc1949 / latest [release](https://github.com/ropensci/gutenbergr/releases/tag/v0.2.3)
