### ISSUE TITLE
Update metadata / refactor metadata code

### ISSUE THREAD

**Issue by noamross** [ropensci/gutenbergr#32]
The package metadata, which is currently derived from scraping the Gutenberg website, is out of date. We'd like this to be complete along so we can submit it as part of getting this back on CRAN with a maintainer transfer (#30) 

 @Myfanwy has helpfully investigated and describes the issue as follows:

> The package depends on some python libraries that are broken...I was unable to run the code that would bring the metadata up to date.
>
> Separately, I investigated the Gutenberg Projects API and they have quite a few machine-readable options that (I think) might be more straightforward instead of web-scraping the metadata, which seems to be the current approach by the package.  However I couldn't immediately reproduce all of the intermediate fields that the gutenbergr creates in the script that tidies the web-scraping results in the time that I had to work on it, so I stopped.
>
> Seems like there are a few options, here in increasing order of commitment/time:
>
> 1) we update the documentation to fix the CRAN issue (#31) , but do not update the metadata
> 2) someone who is more experienced with python libraries can take a stab at updating the metadata with the existing script, and then I can update the documentation for CRAN
> 3) We re-factor the package for a new major release that will be more stable going forward, but the updates to the core metadata may have breaking changes to previous code.

**Comment by noamross** [comment]
I would suggest (2) for a balance of expedience and effort. @jonthegeek, would you be willing to look at this?

**Comment by jonthegeek** [comment]
@noamross My python chops are pretty weak, but I'll take a look at this this weekend to see if I can either figure it out or figure out who to ask about it. 

I feel like an ideal fix might be a bit of a combination of 2 and 3, where we try to get the data from the APIs but figure out how to match the existing fields. I'll probably look at both to some degree, I'm mostly including this paragraph to remind myself what I was thinking might be fruitful.

**Comment by jonthegeek** [comment]
Closed by #33.
