### ISSUE TITLE
Update data-raw to R

### ISSUE THREAD

**Issue by jonthegeek** [ropensci/gutenbergr#36]
Right now the initial steps in data-raw are in Python, and are thus opaque to the maintainers. That's a recipe for eventual disaster.

We should rewrite the full process to use R, so we can maintain it.

**Comment by jonthegeek** [comment]
Consider pulling this data off to its own data-only package, since the update schedule on the data should be different than the schedule on the functions for getting and cleaning things.

**Comment by jonthegeek** [comment]
We can also get rid of 0.3MB of gutenberg_metadata.rda by removing the duplicate author info. I'll have to see if that would be annoying, but we can probably make a function or functions to combine the dfs as needed.

**Comment by msperlin** [comment]
Hi Jon,

When fixing the metadata files, I searched for a R alternative to read the metadata files in the rdf format. Surprisingly, I found none. 

However, there is a catalog .csv file at [guntemberg](https://www.gutenberg.org/cache/epub/feeds/), but the data format is different and might require other changes in the package. Particularly, the information of whether a  book has a .txt file is only found in the rdf files.

One idea is to:
1) use the csv file for "simple" cataloging. This makes sure the  user has a up to date access to the books. 
2) set up, in another repo, a github action (GA) for downloading and parsing the whole metadata files. We can run this GA weekly, and download the metadata from the repo.

**Comment by jonthegeek** [comment]
[rdflib](https://cran.r-project.org/package=rdflib) looks promising, but I haven't dug into the files to see what it would take.

**Comment by msperlin** [comment]
> 

did not work for me.. but let me know how it goes..

**Comment by jonthegeek** [comment]
I'm making progress on this using xml2 to parse a bit more directly, rather than an RDF-specific tool.

**Comment by jonthegeek** [comment]
I also found at least 1 issue with the current process! It there's more than 1 author, we log it as having 0 authors. For the first pass I'm going to make the same error (to make sure I match what we already have), but I'll make notes of things like that as I go through so we can fix it!

**Comment by Myfanwy** [comment]
Thanks guys - should we get the author issue patched before we submit to CRAN?

**Comment by jonthegeek** [comment]
> Thanks guys - should we get the author issue patched before we submit to CRAN?

We can skip this issue before cran I think. Let's get the package maintainer fixed, then we can make further improvements.

**Comment by Myfanwy** [comment]
Have been brainstorming this; we can re-factor the metadata download steps with a single R script that uses `download.file()` + XPath, since rdf is just an extension/version of XML.  Not sure when it'll happen, but I've started a dev branch and will push when it's working

**Comment by jonthegeek** [comment]
@Myfanwy I have this mostly done, using exactly that approach. Coming soon!

**Comment by Myfanwy** [comment]
@jonthegeek great minds!  Right on

**Comment by Myfanwy** [comment]
> I'm making progress on this using xml2 to parse a bit more directly, rather than an RDF-specific tool.

Somehow missed this before I wrote my comment - sorry!  Looking forward to the new approach!  Also, the XML/XPath suggestion was a friend's, to give credit where it's due - I'm just interested in learning XPath :)

**Comment by jonthegeek** [comment]
Shockingly enough... for me it was a suggestion from ChatGPT. The actual code was way wrong, but the approach is proving fruitful!

**Comment by jonthegeek** [comment]
(I'm mostly thinking out loud in this comment)

I'm trying to sort out what we should do about multi-author works. I think we're going to have to restructure some things to make them make sense.

Since this package is used in a LOT of examples of how to parse text, I don't want to dramatically change anything (such that those examples stop working). But the `gutenberg_meta` dataset is constructed in such a way that it assumes each work can only have one author (well, or zero authors), and that's just not the case for quite a few works. And making it not behave that way looks like it would break quite a few things.

I think I'm going to update the datasets to use either list columns or have more than one row per item where appropriate (such as the authors), but then update the corresponding functions that use them such that they deal with that change. Hopefully I can still make the examples work the same.

Now to see what that means in practice...
