### ISSUE TITLE
Move actual download tests to GHA or manual only

### ISSUE THREAD

**Issue by jonthegeek** [ropensci/gutenbergr#37]
Most of the time, we should assume that the gutenberg side isn't changing, and focus on making sure our code works. Get rid of the test-download.R version of tests, at least as far as the main test suite goes. Add a GHA that checks that side of things from time to time, and maybe an easy way to check it manually (such as a switch in the mock).

**Comment by Myfanwy** [comment]
Changed examples to dontrun/ to cut down on server time for now; will work on this for the next release

**Comment by Myfanwy** [comment]
This has come up via the 'fail gracefully' CRAN email - @jonthegeek , I'm going to lay out a plan once I think I understand the issue, can I send you a bat signal to check it over when it's ready?

**Comment by jonthegeek** [comment]
Sure!

**Comment by Myfanwy** [comment]
One of the problems I'm having is that I can't always reproduce the issue they're referencing [here](https://www.stats.ox.ac.uk/pub/bdr/donttest/gutenbergr.out).  However, I understand that  CRAN would like functions like `gutenberg_download()` to do something other than issuing an error when it can't download a title.  This is at odds with user experience, as we would like our users to *know* when the function has failed to download their book.

I haven't had nearly as much time as I need to really understand these options or ones I haven't come across yet, but as I understand it, we could:

1) use skip_cran() or remove the tests and examples, which I assume would only annoy them greatly
2) use `@examplesIf interactive()`, as [here](https://github.com/DPIRD-FSI/weatherOz/blob/f75219ec060c3cf59afbc02dab9203c40eccdade/R/get_ag_bulletin.R#L36)
3) implement something similar to this aptly-titled [`fail_gracefully()` function](https://github.com/lgnbhl/wikisourcer/blob/master/R/utils.R).  Not sure what kinds of compromises/changes this would entail to `gutenberg_download()`.
4) ?

@jonthegeek, am I understanding this right?  I will not be able to do any of these before they kick it off CRAN again tomorrow, I'm really sorry - but we wanted to refactor a few things anyway, so maybe this is the chance to do that?

**Comment by jonthegeek** [comment]
I definitely wouldn't download in the examples. There are too many variables, including that it means you can't download the gz and then later install the package when you're offline (I could imagine that sort of thing happening when someone is setting up a company machine). So use `@examplesIf interactive()` in any examples that hit the internet (which is probably all examples).

For tests... `skip_on_cran()` is probably an acceptable starts for any that hit the internet. When I have some time (probably in a week or two), I can update them to use proper mocks, but until then I'd skip on cran.

I'd definitely resist any push to fail without erroring when there's no internet. The point of the function is to download. If it can't do that, it has failed. But I think sometimes "don't crash examples if the user doesn't have internet" is interpreted as "don't throw errors (from normal function use) when the user doesn't have internet" and that's not what they mean.

**Comment by Myfanwy** [comment]
Finally made this into a pull request - apologies, I didn't have a computer for awhile.

**Comment by jonthegeek** [comment]
I'll take a look at this soon! Adding it to my to-do list!
No worries about the timeline!

**Comment by Myfanwy** [comment]
Addressed in [latest release](https://github.com/ropensci/gutenbergr/releases/tag/v0.2.4)
