### ISSUE TITLE
Release gutenbergr 0.2.2

### ISSUE THREAD

**Issue by Myfanwy** [ropensci/gutenbergr#42]
First release:

* [x] `usethis::use_cran_comments()`
* [x] Update (aspirational) install instructions in README
* [x] Proofread `Title:` and `Description:`
* [x] Check that all exported functions have `@return` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [x] `git pull`
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] `git push`

Submit to CRAN:

* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `git push`
* [x] `usethis::use_github_release()`

**Comment by Myfanwy** [comment]
@jonthegeek the submission was rejected because of an HTML validation problem:

```
Found the following HTML validation problems:
gutenberg_get_mirror.html:25:1 (gutenberg_get_mirror.Rd:19): Warning: <a> illegal characters found in URI
```

See [this log](https://win-builder.r-project.org/incoming_pretest/gutenbergr_0.2.2_20221213_053035/Debian/00check.log) for details.

Is this an issue with the "[" and "]" characters in the wget URL/URI recommended by Project Gutenberg?  If so, is there a way to escape these characters to pass the automated checks?

**Comment by jonthegeek** [comment]
@Myfanwy checking. It probably isn't that, but I'm not sure yet what it is!

**Comment by Myfanwy** [comment]
ok - I found a few more instances where http needed to go to https, as well.  I will push changes momentarily

**Comment by jonthegeek** [comment]
README.Rmd (and thus README.md) have a couple hard links to our code of conduct at `/blob/master/`, and those are now `/blob/main/`. Dunno if that's part of the issue.

OH, looking at the gutenberg_get_mirror documentation, I wouldn't make that a `\url` tag. Just show it in quotes. It isn't meant to be human-browsable. Honestly I'd probably remove it altogether; that doesn't give the user useful information. Change it to:
> Get the recommended mirror for Gutenberg files and set the global \code{gutenberg_mirror} options.

**Comment by Myfanwy** [comment]
ok - the blob/ paths were fixed in 08937e145; I'll make this change and re-run rhub/win-dev checks

**Comment by Myfanwy** [comment]
Successfully published to [CRAN](https://github.com/ropensci/gutenbergr/releases/tag/v0.2.3)

**Comment by jonthegeek** [comment]
Congrats, maintainer! @Myfanwy
