### ISSUE TITLE
Release gutenbergr 0.2.4

### ISSUE THREAD

**Issue by Myfanwy** [ropensci/gutenbergr#45]
First release:

* [x] `usethis::use_cran_comments()`
* [x] Update (aspirational) install instructions in README
* [x] Proofread `Title:` and `Description:`
* [x] Check that all exported functions have `@return` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#sec-code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [x] `git pull`
* [x] `urlchecker::url_check()`
* [x] `devtools::build_readme()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `git push`

Submit to CRAN:

* [x] `usethis::use_version('patch')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version(push = TRUE)`

**Comment by jonthegeek** [comment]
Any progress?

**Comment by Myfanwy** [comment]
> Any progress?

Working on it this morning - will try to get it submitted today. After that point we should probably request a new maintainer, I am clearly spread too thin I'm sorry

**Comment by jonthegeek** [comment]
@Myfanwy I think I can take it over. It turns out it kinda fits with some of the other stuff I'm working on after all!

**Comment by Myfanwy** [comment]
@jonthegeek you are the kind of stellar maintainer this package needs and deserves!  Should I still do this release, and then you can do the next one with the maintainer update?

**Comment by Myfanwy** [comment]
@jonthegeek submitted yesterday, rejected today (comments added below):

"Version contains large components (0.2.3.9100) Please use a more serious
version number." - _This is my fault, I forgot to run use_version("patch") - I remembered immediately after submitting to CRAN_ :-\

"\dontrun{} should only be used if the example really cannot be executed
(e.g. because of missing additional software, missing API keys, ...) by
the user. That's why wrapping examples in \dontrun{} adds the comment
("# Not run:") as a warning for the user. Does not seem necessary.
Please replace \dontrun with \donttest." _@jonthegeek I will try this, but I think we wrapped in dontrun{} to limit server time on CRAN didn't we?_

"Please fix and resubmit."

**Comment by jonthegeek** [comment]
I think we likely want examplesIf. https://r-pkgs.org/man.html#sec-man-examples-dependencies-conditional-execution

That way the user can easily add them, but they won't run on CRAN. Probably `@examplesIf interacrive()`

**Comment by Myfanwy** [comment]
right - we added `@examplesIf interactive()` to all the `gutenberg_download()` examples in this new release - the last two remaining instances of `\dontrun are in the `data.R` script, demonstrating how to find and examine the metadata.
