### ISSUE TITLE
Add link to wikipedia in metadata

### ISSUE THREAD

**Issue by lauravana** [ropensci/gutenbergr#56]
Having a link to the wikipedia page would be useful for different task such as character identification based on plot summaries or on character lists. There is a wikipedia template for gutenberg books:

https://en.wikipedia.org/wiki/Template:Gutenberg_book

**Comment by jonthegeek** [comment]
I like this suggestion, but it's out of scope for this package. We want to keep our focus on Project Gutenberg itself. I'll consider whether it might make sense to add this data when we split off the data part of this package. Thanks for the suggestion!
