### ISSUE TITLE
Fix covr action

### ISSUE THREAD

**Issue by jonthegeek** [ropensci/gutenbergr#69]
I think ropensci might have to do something, but I might, too. Sort that out.

**Comment by jrdnbradford** [comment]
@jonthegeek I had to resolve something similar when I took over maintenance of [ropensci/robotstxt](https://github.com/ropensci/robotstxt). Try signing in to https://app.codecov.io/gh/ropensci/gutenbergr/config/general with your GitHub account that has admin access over this repo and see if you can hit the activate button:

![image](https://github.com/user-attachments/assets/85cdbabd-fe53-4def-bf8d-80ac5866f4ea)

**Comment by jonthegeek** [comment]
That did it! Thanks!
