### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by datalabgh** [ropensci/gutenbergr#7]
I keep getting connection timeout although my internet is active. Specifically, this error message:

> Error in open.connection(con, "rb") : Timeout was reached_

I only downloaded the package yesterday.

**Comment by hrapgc** [comment]
Your issue might be related to the one I experienced with gutenberg_download.  Are you behind a firewall?  I have the problem only if the computer needs to be aware of the proxy settings.  Free of a firewall, there's no problem.  Does your problem arise if you don't need a proxy?

**Comment by jonthegeek** [comment]
I'm closing this issue for now.

If someone has this issue in the future and sees this thread, please include more information about your system, and the result of `gutenberg_get_mirror()`.
